### PR TITLE
add issuer information card

### PR DESCRIPTION
**Pull request by Bookcliff**
Added a separate issuer information card

image

On offering page, instead of repeating the issuer information, dynamically render a button to the issuer info 

image

- [x] cursory code review
- [x] cleaned unneeded code

### CODE REVIEW

**Comment by Namaskar-1F64F** [comment]
image
can you make the issuer information look like the bond information panel above it? 

I think no subtitle looks better as it's pretty self-explanatory

**Comment by Namaskar-1F64F** [comment]
looks good otherwise. I think the duplicated button of issuer information and the bond panel's learn more is fine. better to have the user see it than not know about it

**Comment by Namaskar-1F64F** [comment]
maybe copy what the bond information looks like, but do it for the issuer instead ? 
image

**Comment by Bookcliff** [comment]
Fixed!

image

**Comment by Namaskar-1F64F** [comment]
this looks awesome, nice work

**Pull request merged**
