### PR TITLE
Removed minPrice button

### PR DESCRIPTION
**Pull request by Bookcliff**
Removed the minPrice button.

Please let me know if there's a better way of doing this. I think it would be confusing to have the button there but disabled which is why I just removed the code.

image

### CODE REVIEW

**Comment by Bookcliff** [comment]
Fixed! Added the disabled={isGoerli} attribute to the button component.

https://www.loom.com/share/7decc20a51844689b48d8e7a97959f4a

**Comment by Namaskar-1F64F** [comment]
I do not think disabled is a good idea. the experience now is a button that seems like it should work but doesn't do anything. I think it should be completely hidden on testnet

**Comment by Bookcliff** [comment]
Fixed!

image

**Review by Namaskar-1F64F — APPROVED** [review]
lgtm!

**Pull request merged**
